version: '3.7'

services:

  mongodb:
    image: mongo:7.0.3-rc1
    container_name: mongodb
    restart: always
    env_file:
      - ./mongodb/.env
    volumes:
      - mongodb-volume:/data/db
    ports:
      - "27017:27017"

volumes:
  mongodb-volume: